# Question 5 

In [1]:
import os
os.chdir(r'/Users/professortu/Documents/BOEK')
import sys
sys.path.append(r'/Users/professortu/Documents/BOEK')

import pandas as pd 
import numpy as np 
import statsmodels.api as sm 

Read the Excel file

In [17]:
data = pd.read_excel('KTdata.xlsx')
print(data.columns)

Index(['person', 'lnwage', 'educ', 'exp', 'ability', 'moedu', 'faedu', 'sibs'], dtype='object')


In [25]:
# Prepare y and X1
y = data['lnwage']
X1 = data[['educ', 'exp', 'ability']]
X1 = sm.add_constant(X1)

# Prepare X2
X2 = data[['moedu', 'faedu', 'sibs']]

# Combine X1 and X2
X = pd.concat([X1, X2], axis=1)

# Print the adjusted X
print(X)


    const  educ  exp  ability  moedu  faedu  sibs
0     1.0    13    1     1.00     12     12     1
1     1.0    15    4     1.50     12     12     1
2     1.0    10    1    -0.36     12     12     1
3     1.0    12    1     0.26     12     10     4
4     1.0    15    2     0.30     12     12     1
5     1.0    15    2     0.44     12     16     2
6     1.0    15    3     0.91     12     12     1
7     1.0    13    4     0.51     12     15     2
8     1.0    13    2     0.86     12     12     2
9     1.0    11    5     0.26     12     12     1
10    1.0    12    1     1.82     16     17     2
11    1.0    13    4    -1.30     13     12     5
12    1.0    12    3    -0.63     12     12     2
13    1.0    12    6    -0.36     10     12     2
14    1.0    12    3     0.28     12     12     3


### Question a:
Compute the least squares regression coefficients in the regression of $y$ on $X_1$. Report the coefficients.



In [23]:
model_a = sm.OLS(y, X1).fit()
print(model_a.summary())

                            OLS Regression Results                            
Dep. Variable:                 lnwage   R-squared:                       0.183
Model:                            OLS   Adj. R-squared:                 -0.039
Method:                 Least Squares   F-statistic:                    0.8232
Date:                Mon, 23 Dec 2024   Prob (F-statistic):              0.508
Time:                        00:14:36   Log-Likelihood:                 1.0519
No. Observations:                  15   AIC:                             5.896
Df Residuals:                      11   BIC:                             8.728
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6636      0.619      2.690      0.0

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:418: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=15 observations were given.
  return hypotest_fun_in(*args, **kwds)


### Question b:
Compute the least squares regression coefficients in the regression of $y$ on $X_1$ and $X_2$. Report the coefficients.

In [26]:
model_b = sm.OLS(y, X).fit()
print(model_b.summary())

                            OLS Regression Results                            
Dep. Variable:                 lnwage   R-squared:                       0.625
Model:                            OLS   Adj. R-squared:                  0.344
Method:                 Least Squares   F-statistic:                     2.223
Date:                Mon, 23 Dec 2024   Prob (F-statistic):              0.146
Time:                        00:32:46   Log-Likelihood:                 6.8909
No. Observations:                  15   AIC:                            0.2183
Df Residuals:                       8   BIC:                             5.175
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.7764      1.002     -0.775      0.4

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:418: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=15 observations were given.
  return hypotest_fun_in(*args, **kwds)


### Question c:
**Regress each of the three variables in** $X_2$ **on all the variables in** $X_1$ **and compute the residuals from each regression. Arrange these new variables in the** $15 \times 3$ **matrix** $\tilde{X}_2$. **What are the sample means of these three variables? Explain the finding.**


In [27]:
residuals_matrix = []

for col in X2.columns:
    model = sm.OLS(data[col], X1).fit()
    residuals = model.resid
    residuals_matrix.append(residuals)

X_tilde_2 = np.column_stack(residuals_matrix)

sample_means = X_tilde_2.mean(axis=0)

print("Residuals Matrix (X~2):")
print(X_tilde_2)
print("\nSample Means of Each Variable in X~2:")
print(sample_means)

Residuals Matrix (X~2):
[[-1.00237722 -1.22150878 -0.68216791]
 [-0.18294807 -1.71475472 -0.01293517]
 [-0.69940629  0.04565311 -1.69310393]
 [-0.74823444 -2.54894445  1.74593351]
 [-0.07794267 -0.66525293 -1.21534339]
 [-0.15273807  3.21256759 -0.10061506]
 [-0.1357879  -1.19873093 -0.6059444 ]
 [ 0.06355362  2.20274575  0.24481681]
 [-0.65953284 -1.10045385  0.31261505]
 [ 0.18275722 -0.52668416 -0.78149877]
 [ 2.41833118  3.08962704  1.02433486]
 [ 2.03055121  0.7823519   1.76154346]
 [ 0.26334854  0.22551886 -0.76438827]
 [-1.07675276 -0.01348665 -0.21459264]
 [-0.22282152 -0.56864777  0.98134585]]

Sample Means of Each Variable in X~2:
[-2.13162821e-15  0.00000000e+00 -1.74675089e-15]


### Question d:

**Compute the** $R^2$ **for the regression of** $y$ **on** $X_1$ **and** $X_2$. **Repeat the computation for the case in which the constant term is omitted from** $X_1$. **What happens to** $R^2$?

In [28]:
#y on X1 and X2
# Extract y_actual (observed values)
y_actual = y.values

# Extract y_predicted (fitted values)
y_predicted = model_b.fittedvalues.values

# Calculate the mean of y_actual
y_mean = np.mean(y_actual)

# Calculate SS_total (total sum of squares)
SS_total = np.sum((y_actual - y_mean) ** 2)

# Calculate SS_residual (residual sum of squares)
SS_residual = np.sum((y_actual - y_predicted) ** 2)

# Calculate R-squared manually
R_squared = 1 - (SS_residual / SS_total)

# Print the results
print("SS_total:", SS_total)
print("SS_residual:", SS_residual)
print("R-squared (manual):", R_squared)
print("R-squared (model):", model_b.rsquared) 

SS_total: 0.9346933333333335
SS_residual: 0.3504248263194957
R-squared (manual): 0.6250911247330722
R-squared (model): 0.6250911247330722


In [29]:
#y on X1 and X2 without constant
X11 = data[['educ', 'exp', 'ability']]
X12 = pd.concat([X11, X2], axis=1)
model_c = sm.OLS(y, X12).fit()
print(model_c.summary())

                                 OLS Regression Results                                
Dep. Variable:                 lnwage   R-squared (uncentered):                   0.994
Model:                            OLS   Adj. R-squared (uncentered):              0.990
Method:                 Least Squares   F-statistic:                              255.5
Date:                Mon, 23 Dec 2024   Prob (F-statistic):                    1.57e-09
Time:                        01:13:32   Log-Likelihood:                          6.3484
No. Observations:                  15   AIC:                                    -0.6967
Df Residuals:                       9   BIC:                                      3.552
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:418: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=15 observations were given.
  return hypotest_fun_in(*args, **kwds)


In [30]:
# Extract y_predicted (fitted values)
y_predicted_c = model_c.fittedvalues.values
# Calculate SS_residual (residual sum of squares)
SS_residual_c = np.sum((y_actual - y_predicted_c) ** 2)
# Calculate R-squared manually
R_squared_c = 1 - (SS_residual_c / SS_total)

# Print the results
print("SS_total:", SS_total)
print("SS_residual:", SS_residual_c)
print("R-squared (manual):", R_squared_c)
print("R-squared (model):", model_c.rsquared) 

SS_total: 0.9346933333333335
SS_residual: 0.37671184257317875
R-squared (manual): 0.5969674446807738
R-squared (model): 0.9941638042902796


### Question e:
Compute the adjusted $R^2$ for the full regression including the constant term. Interpret your result.

In [31]:
# Number of observations and independent variables
n = len(y_actual)  # Number of observations
k = X.shape[1] - 1  # Number of independent variables (excluding constant)
# Calculate Adjusted R-squared manually
R_squared_adj = 1-((1-R_squared)*(n-1))/(n-k-1)
# Print results
print("R-squared (adjusted, manual):", R_squared_adj)
print("R-squared (adjusted, model):", model_b.rsquared_adj)

R-squared (adjusted, manual): 0.3439094682828763
R-squared (adjusted, model): 0.3439094682828763


### Question f:
Referring to the result in part c, regress $y$ on $X_1$ and $\tilde{X}_2$. How do your results compare to the results of the regression of $y$ on $X_1$ and $X_2$? The comparison you are making is between the least squares coefficients when $y$ is regressed on $X_1$ and $M_1X_2$, and when $y$ is regressed on $X_1$ and $\tilde{X}_2$. Derive the result theoretically. (Your numerical results should match the theory, of course.)